### ISSUE TITLE
Error while importing: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

### ISSUE THREAD

**Issue by Avishka-Perera** [WooKyoungHan/JDEC#2]
Hi @WooKyoungHan ,

Amazing paper actually. I'm following this work but unfortunately getting the above error when running the scripts. I am using ubuntu 22.02. These are the steps to recreate the above issue;
* Comment the `- dct-manip==0.2.3` line in environment.yaml
* Create and activate the environment
* Change the environment root in the dct_mainp/setup.py (include_dirs, library_dirs, extra_objects, and headers paths)
* cd to dct_mainp and do `pip install .`
* In a python script (my_script.py), add the following lines
    ```python
    import torch
    import dct_manip as dm
    ```
* This will throw the following error
```
Traceback (most recent call last):
  File "temp.py", line 2, in <module>
    import dct_manip as dm
ImportError: /home/avishka/anaconda3/envs/jdec/lib/python3.6/site-packages/dct_manip.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv
```

Any help would be highly appreciated.

Kind regards,
Avishka Perera

**Comment by Arcitec** [comment]
@WooKyoungHan Your work looks incredibly good and I am so excited to try it, but unfortunately have the same issues:

Conda environment cannot be created, because `dct-manip` is not the name of a pip package.

```
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement dct-manip==0.2.3 (from versions: none)
ERROR: No matching distribution found for dct-manip==0.2.3

failed

CondaEnvException: Pip failed
```

I found out that it comes from the "RGB No More" project though:

https://github.com/JeongsooP/RGB-no-more

But they do not publish a pip package.

So I suppose I'll have to install it manually as @Avishka-Perera did. But it seems like that would lead to other problems anyway. It looks like `dct_manip` is a module that must be compiled specifically for Python 3.6 manually with [these instructions](https://github.com/JeongsooP/RGB-no-more?tab=readme-ov-file#usage). Except I see that they recommend building with Python 3.10. But JDEC wants Python 3.6. Hmm.

Do you have any advice how we can get your project to execute on our systems? There's some steps missing in the repo. And the conda environment YAML definitely shouldn't refer to the non-existent dct-manip package. :)

PS: The `enviroment.yaml` should be renamed to `environment.yaml` in your repo. It's a typo which mismatches with the readme instructions. :)

**Comment by Arcitec** [comment]
Okay... so... I see that JDEC already contains the `dct_manip` subdirectory and that the code is identical to the [latest upstream](https://github.com/JeongsooP/RGB-no-more/blob/main/dct_manip/dct_manip.cpp). I also didn't notice that you already include the instructions for compiling dct_manip.

Here are the revised installation instructions.

1. Rename `enviroment.yaml` to `environment.yaml`
2. Edit `environment.yaml` to remove `dct-manip==0.2.3`. I am guessing that you auto-generated the `environment.yaml` from Conda and it added that incorrect line automatically, since you had manually installed dct_manip.
3. Follow the [JDEC installation instructions](https://github.com/WooKyoungHan/JDEC/tree/main?tab=readme-ov-file#installation).
4. Fail anyway, because Conda's `jpegio` installation instruction fails to find the necessary libraries on Fedora. It finds them all, but complains that they are the wrong version. I even tried to manually build a [newer jpegio version](https://github.com/dwgoon/jpegio) but failed with the same error. Looks like the JDEC project may only be able to compile on Ubuntu with its older system libraries, and even @Avishka-Perera had problems on a new version of Ubuntu. So I am guessing that JDEC requires the exact "Ubuntu 20.04" that was mentioned in the readme. :/ Sadly I have to give up on JDEC even though it looked like an incredible project...

<details>
  <summary>Click for error log.</summary>

```
  gcc -pthread -B /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I. -I/tmp/pip-build-env-1yxj796e/overlay/lib/python3.6/site-packages/numpy/core/include -I/tmp/pip-install-l1muf_jx/jpegio_f62d7ba73e9a4f46b67f705dac07f4f3 -I/tmp/pip-install-l1muf_jx/jpegio_f62d7ba73e9a4f46b67f705dac07f4f3/jpegio/libjpeg/include -I/tmp/pip-install-l1muf_jx/jpegio_f62d7ba73e9a4f46b67f705dac07f4f3/jpegio -I/home/johnny/.local/share/miniconda/envs/jdec/include/python3.6m -c jpegio/componentinfo.cpp -o build/temp.linux-x86_64-3.6/jpegio/componentinfo.o -w -fPIC -m64
  cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  g++ -pthread -shared -B /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat -L/home/johnny/.local/share/miniconda/envs/jdec/lib -Wl,-rpath=/home/johnny/.local/share/miniconda/envs/jdec/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/jpegio/componentinfo.o -o build/lib.linux-x86_64-3.6/jpegio/componentinfo.cpython-36m-x86_64-linux-gnu.so
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: /lib64/libm.so.6: unknown type [0x13] section `.relr.dyn'
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: skipping incompatible /lib64/libm.so.6 when searching for /lib64/libm.so.6
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: /lib64/libm.so.6: unknown type [0x13] section `.relr.dyn'
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: skipping incompatible /lib64/libm.so.6 when searching for /lib64/libm.so.6
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: cannot find /lib64/libm.so.6
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: /lib64/libm.so.6: unknown type [0x13] section `.relr.dyn'
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: skipping incompatible /lib64/libm.so.6 when searching for /lib64/libm.so.6
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: /lib64/libm.so.6: unknown type [0x13] section `.relr.dyn'
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: skipping incompatible /lib64/libm.so.6 when searching for /lib64/libm.so.6
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: /lib64/libmvec.so.1: unknown type [0x13] section `.relr.dyn'
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: skipping incompatible /lib64/libmvec.so.1 when searching for /lib64/libmvec.so.1
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: /lib64/libmvec.so.1: unknown type [0x13] section `.relr.dyn'
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: skipping incompatible /lib64/libmvec.so.1 when searching for /lib64/libmvec.so.1
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: cannot find /lib64/libmvec.so.1
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: /lib64/libmvec.so.1: unknown type [0x13] section `.relr.dyn'
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: skipping incompatible /lib64/libmvec.so.1 when searching for /lib64/libmvec.so.1
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: /lib64/libmvec.so.1: unknown type [0x13] section `.relr.dyn'
  /home/johnny/.local/share/miniconda/envs/jdec/compiler_compat/ld: skipping incompatible /lib64/libmvec.so.1 when searching for /lib64/libmvec.so.1
  collect2: error: ld returned 1 exit status
  error: command 'g++' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for jpegio
ERROR: Could not build wheels for jpegio which use PEP 517 and cannot be installed directly

failed

CondaEnvException: Pip failed
```
</details>

**Comment by Arcitec** [comment]
I was curious about using Ubuntu 20.04 exactly as the JDEC readme says.

- So I created a 20.04 virtual machine. Selected minimal install.
- Ran `sudo apt install git gcc g++`. This is necessary because the JDEC conda `environment.yaml` is misconfigured and is missing gcc/g++. It's also worth noting that RGB-no-More's repo has instructions for installing EXACT versions of those tools into Conda instead.
- Ran `conda env create --file environment.yaml` to create the basic environment. Successful. Jpegio was compiled successfully.
- Did the rest of the JDEC instructions to compile dct-manip too. Successful.
- Tried making a `what.py` file with these lines:
```py
import torch
import dct_manip as dm
```
- While conda environment is active, I ran `python what.py` and had no errors, @Avishka-Perera. So either try following the instructions I just mentioned, and if that isn't the problem then you need to downgrade to Ubuntu 20.04.
- And despite just being a virtual machine with no GPU passthrough, I was also able to run `python test.py` (the official model loader). So it certainly seems like everything works in Ubuntu 20.04.

I am tempted to try using Distrobox or Docker to run a Ubuntu 20.04 "container" with GPU passthrough on my native Fedora 40 system. I guess I'll try that ~~tomorrow~~ can't sleep, trying it now...

**Comment by Arcitec** [comment]
# Okay here's the instructions for running JDEC on ANY distro:

Install NVIDIA driver on the Host OS.

Install Distrobox.

Create the Distrobox container with NVIDIA driver integration:

```sh
distrobox create --nvidia --name ubuntu-20.04 --image docker.io/library/ubuntu:20.04
```

Enter it for the first time and wait for it to install basic packages:

```sh
distrobox enter ubuntu-20.04
```

You are now in a prompt that's a mix of your host's shell and kernel and your "container" environment's libraries and binaries. The container will prefer its own libraries and binaries, but will use your host's as fallback.

What this means is that if you run a command such as `nvidia-smi -q`, you will see errors about missing GLIBC libraries, because it runs your host's `nvidia-smi` which was made for a different GNU libc than the Ubuntu 20 container. This is a good sign that the container environment is working. And it will still display your GPU's details and host driver version, meaning the GPU and driver is properly linked into the container.

It also means that your host's existing Miniconda installation still exists and doesn't need to be installed again.

Now let's do the rest of the commands.

Install the Ubuntu versions of git (we need the Ubuntu version), gcc and g++:

```sh
sudo apt install git gcc g++
```

(If you open a separate terminal to check the host's `gcc --version` it will show your host's version. Mine was 14.2.1. And inside the distrobox terminal it will instead show Ubuntu 20's gcc version, which was 9.4.0 for me. This confirms that the binary override inside the container is working properly.)

Get the JDEC code:

```sh
git clone https://github.com/WooKyoungHan/JDEC.git
cd JDEC
```

~~Fix the issues (at least until #4 is merged).~~ Update: It's merged.

~~Rename `enviroment.yaml` to `environment.yaml`.~~

~~Edit `environment.yaml` to remove `dct-manip==0.2.3`.~~

Now follow the [JDEC installation instructions](https://github.com/WooKyoungHan/JDEC/tree/main?tab=readme-ov-file#installation), by running those commands inside the Distrobox system. If you need to know the Conda environment path for editing the `dct_manip/setup.py` file, then look for the jdec environment in the `conda info --envs` list. Mine was at `/home/johnny/.local/share/miniconda/envs/jdec`.

While creating your conda environment, you will see some GLIBC errors from nvidia-modprobe, but you can ignore those. According to the Distrobox author, it means that the distro in the container uses a GLIBC that's too old/too new compared to what the host's NVIDIA driver was compiled for. The official recommendation is to create the container again without `--nvidia` and instead manually install the GPU driver inside the container, but I didn't have to do that, it worked anyway. It's really just a problem with the command line tools (not CUDA/the driver itself), and the tools still seem to work despite those warnings. (But anyway, if the host's NVIDIA driver really doesn't work for you, then you have to delete and create the container again without `--nvidia` and then install the Ubuntu version of NVIDIA drivers inside the container.)

Lastly, edit `test.py` to point at the `jdec.pth` model as the JDEC readme explains already. I set it to `model_path = './jdec.pth'` just to test.

~~Now I only have one last problem remaining: The released model weights `jdec.pth` are not in the same format that `test.py` expects. This exact problem happened when I ran in a pure, clean Ubuntu 20 VM too, so I know it's a problem with the JDEC code.~~ Update: The fixed `jdec.pth` has been uploaded. Thanks a lot!

```
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    model_spec = torch.load(model_path)['model']
  File "/home/johnny/.local/share/miniconda/envs/jdec/lib/python3.6/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/johnny/.local/share/miniconda/envs/jdec/lib/python3.6/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

So... @WooKyoungHan I have *almost* finished a way to run your code on any distro via Distrobox. But the code itself fails to load `jdec.pth` (even when running natively in Ubuntu 20 outside Distrobox). Any idea what's wrong?

~~Edit: It seems like the `jdec.pth` checkpoint is a broken file. I made a separate ticket for that bug: https://github.com/WooKyoungHan/JDEC/issues/3 -- Hopefully that's the final issue. :)~~ Update: The fixed `jdec.pth` has been uploaded. Thanks a lot! :)

**Comment by WooKyoungHan** [comment]
Thank you for your interest in my work. I’ve encountered similar environment-related issues myself, but I was able to resolve them through environment reinstallation and similar solutions. I’d like to express my gratitude to @Arcitec for organizing and submitting a pull request regarding this.

I am still learning about Git and working environments, so I appreciate your patience with any mistakes I might make. As for the checkpoints, their large size seems to be causing upload issues, but I will do my best to resolve this if you can give me some time.

Once again, thank you for your support and interest!

**Comment by Arcitec** [comment]
@WooKyoungHan 

> Once again, thank you for your support and interest!

Hi! :) Your project is very interesting and I can't wait to see it running!

I would be really happy to help you with writing and submitting a clear installation guide when I finally have JDEC running locally (after the checkpoint corruption is solved). :)

> As for the checkpoints, their large size seems to be causing upload issues, but I will do my best to resolve this if you can give me some time.

Yeah, it's difficult to share large files, especially with Git (Git LFS can be hard to configure). I would really recommend creating an account on Huggingface, and then you can use their web interface to upload files. I saw a guide here:

https://huggingface.co/docs/hub/en/models-uploading

Specifically this part about using the web interface to drag and drop model checkpoint files to upload them:

https://huggingface.co/docs/hub/en/models-uploading#using-the-web-interface

:) Hopefully we have a solution with this method.

**Comment by MaY517** [comment]
A big shout-out to @Arcitec, I used your distrobox solution to successfully setup the environment.
But I encounter another error when trying test.py. Could @WooKyoungHan and everyone please provide some advice? Thanks!

          (jdec) ~/JDEC$ python test.py 
          Traceback (most recent call last):
            File "test.py", line 36, in <module>
              model = models.make(model_spec, load_sd=True).cuda()
            File "~/JDEC/models/models.py", line 22, in make
              model = models[model_spec['name']](**model_args)
            File "~/JDEC/models/JDEC.py", line 16, in __init__
              self.encoder_dct = models.make(encoder_spec)
            File "~/JDEC/models/models.py", line 22, in make
              model = models[model_spec['name']](**model_args)
          KeyError: 'swinv2_rgb_nomore_deepir_rgbver'
