### ISSUE TITLE
Checkpoint jdec.pth cannot be loaded. Corrupt file?

### ISSUE THREAD

**Issue by Arcitec** [WooKyoungHan/JDEC#3]
It looks like the uploaded `jdec.pth` file is corrupt (broken).

I downloaded it TWICE and the hashes are as follows:

```sh
$ md5sum jdec.pth
05ffce5ead865671a0049ff8ffe2ca06  jdec.pth
$ sha256sum jdec.pth
521ac625796f40fe51ad4c56ee179e3a8e813a3b5c75d6b7fc9ad4796fa32f91  jdec.pth
$ file jdec.pth  
jdec.pth: Zip archive data, at least v0.0 to extract, compression method=store
$ ls -lh jdec.pth
-rw-r--r--. 1 johnny johnny 215M Oct 18 08:24 jdec.pth
```

I try to run JDEC's `test.py` with `model_path = './jdec.pth'`

Result:

```sh
$ python test.py
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    model_spec = torch.load(model_path)['model']
  File "/home/johnny/.local/share/miniconda/envs/jdec/lib/python3.6/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/johnny/.local/share/miniconda/envs/jdec/lib/python3.6/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

The "central directory" is where zip files store the list of files, and it's stored at the *end* of the archive binary. So the error indicates to me that the PTH file is broken (cut in half).

So I checked it with 7zip to test pth zip/pickle integrity. And it also says that the PTH file is broken. (PyTorch uses ZIP format since v1.6, so that's why I decided to check it with a zip extractor.)

```sh
$ 7z t jdec.pth 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs AMD Ryzen 7 7800X3D 8-Core Processor            (A60F12),ASM,AES-NI)

Scanning the drive for archives:
1 file, 225181696 bytes (215 MiB)

Testing archive: jdec.pth
             
ERRORS:
Unexpected end of archive

--
Path = jdec.pth
Type = zip
ERRORS:
Unexpected end of archive
Physical Size = 225181696

    

Archives with Errors: 1

Open Errors: 1
```

"Unexpected end of archive" means that the file is truncated (missing data/has been cut in half).

It seems like the `jdec.pth` needs to be uploaded again. Maybe share it to [Huggingface](https://huggingface.co/)? It's much better than Google Drive. :) At Huggingface people can see the checksum/hashes and do easier installation.

**Comment by Arcitec** [comment]
I've now compared JDEC.pth against other AI project's PTH files. The other files successfully pass `7z t <file.pth>` check and verify "Everything is OK". Only the JDEC.pth has errors.

So yes it's confirmed that JDEC.pth on Google Drive is a broken file. Would love if you can share it to Huggingface instead. :)

**Comment by TheForgotten69** [comment]
Agreed on the above, same md5 and same issue unfortunately. Would love to test your project, like it was said, if you can upload the checkpoint somewhere or double check the uploaded file in GDrive that would be great!

**Comment by WooKyoungHan** [comment]
I just re-uploaded the model checkpoint, and I will finish hugging face work soon. Thank you for waiting and again thanks for your attention too.

**Comment by TheForgotten69** [comment]
Thanks @WooKyoungHan the new checkpoint works! The checkpoint needs some code change to be able to fully work though. I'll raise a PR.

**Comment by Arcitec** [comment]
@WooKyoungHan Thank you, the new checkpoint file is over 2x bigger and is valid! :clinking_glasses: 

```
$ 7z t jdec.pth

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs AMD Ryzen 7 7800X3D 8-Core Processor            (A60F12),ASM,AES-NI)

Scanning the drive for archives:
1 file, 479446181 bytes (458 MiB)

Testing archive: jdec.pth
--
Path = jdec.pth
Type = zip
Physical Size = 479446181
64-bit = +

Everything is Ok

Files: 2038
Size:       479062572
Compressed: 479446181

$ md5sum jdec.pth                   
s3934878830361233535feba6f62b20c1  jdec.pth

$ sha1sum jdec.pth 
5fa72791c516d8d6331993479818731ae8dd463a  jdec.pth

$ ls -lh jdec.pth
-rw-r--r--. 1 johnny johnny 458M Oct 28 09:52 jdec.pth
```

I also needed the #5 patches to be able to run the code. Let's continue discussion there.

I look forward to the model being on HuggingFace! :)
